### ISSUE TITLE
Not Accessoing Swift files 

### ISSUE THREAD

**Issue by srinadh588** [romsi/VIPERXCodeTemplate#1]
Hi  i created on swift file, i defined one structured there. im not able to Access VIPER created Classes.

**Comment by romsi** [comment]
Can you provide screenshot? Because I'm not sure to understand correctly.

**Comment by srinadh588** [comment]
Im sorry, its problem with Xcode. but can you please provide some good example for swift latest version. i haven't find any application. that doesnt contains V, I, P, E, R modules.

**Comment by romsi** [comment]
Great idea! I will add an example as soon as possible. In the mean time, you should take a look at [my personal project](https://github.com/Mobilette/AniMee) where I'm using VIPER modules.

@srinadh588 open it again if you have need more information.

**Comment by srinadh588** [comment]
@romsi thanks man, i will look forward to your example.
